# Generated by Django 4.2.3 on 2024-02-03 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_employee_uuid_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
