# Generated by Django 4.2.3 on 2024-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_remove_employee_id_alter_employee_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='uuid',
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
