# Generated by Django 4.2.3 on 2024-02-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_remove_employee_uuid_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
